# Generated by Django 4.2.21 on 2025-08-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_image1_alter_project_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='course_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
