# Generated by Django 4.2.21 on 2025-08-16 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_course_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='course_name',
        ),
    ]
